//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mbpros.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public string shortDesc { get; set; }
        public string longDesc { get; set; }
        public string ExtraLongDEsc { get; set; }
    }
}
