//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mbpros.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature_User
    {
        public int FeatureUserID { get; set; }
        public int FeatureID { get; set; }
        public int UserID { get; set; }
        public bool CanView { get; set; }
    }
}
