//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mbpros.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MbprosEntities : DbContext
    {
        public MbprosEntities()
            : base("name=MbprosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Config> Configs { get; set; }
        public DbSet<Feature_User> Feature_User { get; set; }
        public DbSet<FeatureMaster> FeatureMasters { get; set; }
        public DbSet<PatientBilling> PatientBillings { get; set; }
        public DbSet<PatientMaster> PatientMasters { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
